title: "Sumerian Networks"
logo: images/sumnet.png

# Prevent rerunning the notebook
execute:
  execute_notebooks: "off"

# Information about where the book exists on the web
repository:
  url                       : https://github.com/ybordag/sumnet-test  # Online location of your book
  path_to_book              : book/  # Optional path to your book, relative to the repository root
  branch                    : master  # Which branch of the repository should be used when creating links (optional)

# Add Google Colab launch button
launch_buttons:
  colab_url: "https://colab.research.google.com"